FROM opensearchproject/opensearch:2
RUN ./bin/opensearch-plugin remove opensearch-security
#COPY --chown=opensearch-dashboards:opensearch-dashboards opensearch_dashboards.yml /usr/share/opensearch-dashboards/config/
