# Different Approaches to getting results from a input String

## 1. Using OpenSearch without LLM

[plantuml, svg]
----
@startuml
start
:**User Input**:
"Wo sind die Gestellschrauben?";
:Sent to own backend;
:Backend extracts importatant data from the user input;
:Backend constructs an OpenSearch query;
:Backend sends the query to OpenSearch;
:Backend phrases the results in human-readable form;
:Backend sends the results to the frontend;
end
@enduml
----

**Pros:**

- no made up answers, only uses context

- no need for OpenAI

- free

- fast

**Cons:**

- hard to implement

- time-consuming

- no conversation

- difficult to extract important data from the user input

## 2. OpenSearch Conversational Search

[plantuml, svg]
----
@startuml
start
:**User Input**:
"Wo sind die Gestellschrauben?";
:Sent to OpenSearch;
:OpenSearch uses an LLM (gpt3.5-turbo) to generate a response;
:Response sent back to the frontend;
end
@enduml
----

**Pros:**

- easy to implement

- built-in OpenSearch feature

- conversation possible

- conversation memory

**Cons:**

- made up answers

- paid

- hard to configure the LLM

## 3. LLM without OpenSearch

[plantuml, svg]
----
@startuml
start
:**User Input**:
"Wo sind die Gestellschrauben?";
:Sent to own backend;
:Backend constructs an AI prompt;
:Sent to OpenAI with entire DB as context;
:OpenAI uses an LLM (gpt3.5-turbo) to generate a response;
:Response sent back to the frontend;
end
@enduml
----

**Pros:**

- easy to configure the LLM

- flexible prompt generation

- conversation possible

- no need for OpenSearch

**Cons:**

- maybe made up answers

- paid

- need to have the entire DB as context

## 4. LLM for input/output with OpenSearch

[plantuml,svg]
----
@startuml
start
:**User Input**:
"Wo sind die Gestellschrauben?";
:Sent to own backend;
:Backend constructs an AI prompt;
:Sent to OpenAI;
:OpenAI uses an LLM (gpt3.5-turbo) to extract important data;
:Response sent back to the backend;
:Backend constructs an OpenSearch query;
:Backend sends the query to OpenSearch;
:OpenSearch returns the results;
:Backend sends the results to OpenAI;
:OpenAI uses an LLM (gpt3.5-turbo) to phrase the results in human-readable form;
:Response sent back to the backend;
:Backend sends the results to the frontend;
end
@enduml
----

**Pros:**

- no made up answers, only uses context

- accurate results

- human-readable responses

**Cons:**

- a lot of back and forth

- 2 AI calls per request

- paid