@startwbs
* Eisbär (2080h)

** Planung (350h)

*** Projektantrag (20h)
*** PSP (20h)
*** Wireframe (150h)
*** Technologie Evaluierung (100h)
*** Pflichtenheft (50h)

** Durchführung (1700h)

*** Avatar (850h)

**** Modellieren (350h)
**** Animieren (300h)
**** Texturierung (200h)

*** Backend (750h)

**** Datenbankimplementierung (100h)
**** Datenbankanbindung (150h)
**** Usereingaben verarbeiten (400h)
***** LLM
**** Speech to Text (50h)
**** Text to Speech (50h)

*** Frontend (Wire-Frame Umsetzung) (100h)

**** Screendesign (50h)
**** Anzeigen der Ergebnisse von Useranfragen (50h)

** Evaluierung (420h)

*** Testen (350h)

**** Dialog testen (150h)
**** Erfolgsgrad messen (100h)
**** Usability-Test (100h)

*** Übergabe (20h)

*** Dokumentation (50h)
@endwbs