@startwbs
* Eisbär (2080h)
** Planung
*** Projektantrag (5h)
*** PSP (5h)
*** Wireframe (125h)
*** Technologie Evaluierung (100h)
*** Pflichtenheft (10h)
** Durchführung
*** Avatar
**** Modellieren (350h)
**** Animieren (225h)
**** Texturierung (185h)
*** Backend
**** Datenbankanbindung (150h)
**** Usereingaben verarbeiten (400h)
**** Speech to Text (75h)
*** Frontend
**** Screendesign (45h)
**** Anzeigen der Ergebnisse von Useranfragen (30h)
** Testen
*** Dialog testen (150h)
*** Erfolgsgrad messen (125h)
*** Usability-Test (100h)
@endwbs