:toc: macro

= Progress Michael Stützner

toc::[]

== 2025-13-01
=== Trying to change the voice of the polar bear
With Google Chromes standard voice API it only provides a German female voice or an English male voice.
But we are looking for a German male voice. Also, it sounds very robotic and not natural.

We are now trying with 'ResponiveVoice' which is a text-to-speech library that can be used
to create speech-enabled web applications.

https://responsivevoice.org/api/

Implement this script to the project to use the API:

* <script src="https://code.responsivevoice.org/responsivevoice.js?key=YOUR_KEY"></script>

== 2025-20-10
=== Trying out new Avatar on screen
We went to the basement and tried out our new design on the big screen that will be used to
display our project in the future

The person responsible for the screen wasn't there!

== 2025-10-11
=== Meeting with Schubert + AV
AV said he will talk to us on 19th November 2025.

=== Meeting with Hammer
Focus will shift more onto the Avatar. We wrote an email to Prof. Stütz regarding his AI-Video of
the polar bear in the bathtub talking.