:toc: macro

= Progress Michael Stützner

toc::[]

== 2025-13-01
=== Trying to change the voice of the polar bear
With Google Chromes standard voice API it only provides a German female voice or an English male voice.
But we are looking for a German male voice. Also, it sounds very robotic and not natural.

We are now trying with 'ResponiveVoice' which is a text-to-speech library that can be used
to create speech-enabled web applications.

https://responsivevoice.org/api/

Implement this script to the project to use the API:

* <script src="https://code.responsivevoice.org/responsivevoice.js?key=YOUR_KEY"></script>

== 2025-20-10
=== Trying out new Avatar on screen
We went to the basement and tried out our new design on the big screen that will be used to
display our project in the future

The person responsible for the screen wasn't there!

== 2025-10-11
=== Meeting with Schubert + AV
AV said he will talk to us on 19th November 2025.

=== Meeting with Hammer
Focus will shift more onto the Avatar. We wrote an email to Prof. Stütz regarding his AI-Video of
the polar bear in the bathtub talking.

=== Generating new Avatar
==== 1.
* easemate.ai/image-to-video-generator
* Prompt: make the polar bear talk

video::../media/ai-videos/easemate.mp4[]
* Note: Background Color shifts from greyish to white and black tones. The movements in the beginning look weird,
but overall it's a pretty good try. Not perfect tho and definetly not ready to use.

==== 2.
* deevid.ai/image-to-video
* Prompt: the polarbear is moving his mouth as if he was talking

video::../media/ai-videos/deevid.mp4.mp4[]
* Note: Tried it with the polar bear in the bathtub picture. Camera doesn't stay static. A lot of
movement. Polar bear just moves around almost randomly, it doesn't resemble the movement of talking.

==== 3.
* firefly.adobe.com
* Prompt: keep the camera static, make the polar bear talk, only move the mouth and the head, move the legs and arms
a little bit but only just so it looks alive.

video::../media/ai-videos/firefly1.mp4[]
* Note: I tried a longer and more specific prompt to see if that overcomplicates it or if it adds the
last necessary tweaks. ALso tried using Firefly, a more commonly known AI-Model. He now moves his arms and legs A LOT.
 Also his snout is deformed in the beginning.

==== 4.
* firefly.adobe.com
* Prompt: make the polar bear talk

video::../media/ai-videos/firefly2.mp4[]
* Note: Trying out a very simple prompt in Firefly. Now Water splashes out of the tub at the beginning. After he
completely turns to the side and starts talking. Maybe try specifying that the bear shouldn't move?
