### 1. Check Cluster Health
GET http://localhost:9200/_cluster/health

#### CREATING INDEX
PUT http://localhost:9200/articles
Content-Type: application/json

{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 0
  },
  "mappings": {
    "properties": {
      "user": {
        "type": "keyword"
      },
      "message": {
        "type": "text"
      }
    }
  }
}

#### GET INDEX
GET http://localhost:9200/articles

#### GET CLUSTER SETTINGS
GET http://localhost:9200/_cluster/settings
