GET http://localhost:8080/Articles/getArticle/Schrauben

###

POST http://localhost:8080/Articles/getArticle
Content-Type: text/plain

Wo sind die Schrauben die keine Gestellschrauben sind

###

POST http://localhost:8080/Articles/addArticle
Content-Type: application/json

{
  "breite": 10.5,
  "durchmesser": 5.2,
  "hoehe": 15.0,
  "laenge": 20.0,
  "bezeichnung1": "Testartikel",
  "bezeichnung2": "Testbeschreibung",
  "lagereinheitBez": "Stück",
  "lagerort": "Lager A",
  "lagerstand": "10",
  "stellplatz": "Regal 5"
}

###

POST https://it210176.cloud.htl-leonding.ac.at/eisbaer_rag_data/_search
Content-Type: application/json

{"query":{"match":{"text":"Gestell"}},"ext":{"generative_qa_parameters":{"llm_model":"gpt-3.5-turbo","llm_question":"Gestell","context_size":200,"message_size":100,"timeout":15}}}

