# Quarkus Application Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch

spec:
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2.18.0
          env:
            - name: OPENSEARCH_SERVER_SSL_ENABLED
              value: "false"
            - name: OPENSEARCH_SSL_VERIFICATION_MODE
              value: none
            - name: OPENSEARCH_SERVER_SSL_CLIENTAUTHENTICATION
              value: none
            - name: OPENSEARCH_SECURITY_COOKIE_SECURE
              value: "false"
            - name: discovery.type
              value: single-node
            - name: OPENSEARCH_SECURITY_DISABLED
              value: "true"
            - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
              value: Maniac4Something%VeryLong
            - name: DISABLE_SECURITY_PLUGIN
              value: "true"
            # CORS-Konfiguration
            - name: http.cors.enabled
              value: "true"
            - name: http.cors.allow-origin
              value: "*"
            - name: http.cors.allow-methods
              value: OPTIONS,GET,POST
            - name: http.cors.allow-headers
              value: X-Requested-With,Content-Type,Authorization
            - name: http.cors.allow-credentials
              value: "true"
          ports:
            - containerPort: 9200
            - containerPort: 9600
          volumeMounts:
            - name: data
              mountPath: /usr/share/opensearch/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: opensearch-data-0
---

apiVersion: v1
kind: Service
metadata:
  name: opensearch
spec:
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
  selector:
    app: opensearch
---




