#ghcr.io/2425-4bhitm-itp/eisbaer-frontend:938db1f


apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend

spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/2425-4bhitm-itp/eisbaer-frontend:5502426
          imagePullPolicy: Always
          ports:
            - containerPort: 80

      #          startupProbe:
      #            httpGet:
      #              path: /api/q/health
      #              port: 8080
      #            timeoutSeconds: 5
      #            initialDelaySeconds: 30
      #          readinessProbe:
      #            tcpSocket:
      #              port: 8080
      #            initialDelaySeconds: 30
      #            periodSeconds: 10
      #          livenessProbe:
      #            httpGet:
      #              path: /api/q/health
      #              port: 8080
      #            timeoutSeconds: 5
      #            initialDelaySeconds: 30
      #            periodSeconds: 120
      # initContainers:
      #   - name: wait
      #     image: {{ .Values.postgres.image }}
      #     command: ["/bin/bash", "-c", 'until pg_isready -h postgres; do;echo "waiting for database...";sleep 2;done']
      #     env:
      #       - name: POSTGRES_PASSWORD
      #         valueFrom:
      #           secretKeyRef:
      #             name: postgres-admin
      #             key: password
      #       - name: POSTGRES_USERNAME
      #         valueFrom:
      #           secretKeyRef:
      #             name: postgres-admin
      #             key: username
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: frontend