services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=demo
      - POSTGRES_USER=demo
      - POSTGRES_DB=demo
  opensearch:
    image: opensearchproject/opensearch:1.3.19
    healthcheck:
      test: curl --fail http://localhost:9200/_cluster/health
    build:
      context: .
    ports:
      - 9200:9200
      - 9600:9600
    environment:
      - OPENSEARCH_SERVER_SSL_ENABLED=false
      - OPENSEARCH_SSL_VERIFICATION_MODE=none
      - OPENSEARCH_SERVER_SSL_CLIENTAUTHENTICATION=none
      - OPENSEARCH_SECURITY_COOKIE_SECURE=false
      - discovery.type=single-node
      - OPENSEARCH_SECURITY_DISABLED=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Maniac4Something%VeryLong
      - DISABLE_SECURITY_PLUGIN=true
      # CORS-Konfiguration
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-methods=OPTIONS,GET,POST
      - http.cors.allow-headers=X-Requested-With,Content-Type,Authorization
      - http.cors.allow-credentials=true

volumes:
  postgres:

