name: Generate PNG from PUML

on:
  push:
    paths:
      - './documents/psp.puml'  # Triggers only when the psp.puml file changes

jobs:
  generate-png:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install PlantUML
      - name: Install PlantUML
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml

      # Step 3: Generate PNG from the PUML file
      - name: Generate PNG
        run: |
          plantuml ./documents/psp.puml

      # Step 4: Commit and push the new PNG if it has changed
      - name: Commit and push PNG
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./documents/psp.png
          git commit -m "Updated psp.png after psp.puml changes"
          git push
        # Prevents errors if no changes were made
        continue-on-error: true
